### ISSUE TITLE
WindowGroup may have duplicated open windows

### ISSUE THREAD

**Issue by kailuo** [Planetable/Planet#100]
<img width="1072" alt="Screenshot 2022-10-29 at 8 48 55 PM" src="https://user-images.githubusercontent.com/340234/198832385-8bf570ab-70a7-4710-b34b-13e09c9ef636.png">

**Comment by livid** [comment]
There is a new Window API on Ventura. Let's try it?

**Comment by kailuo** [comment]
https://developer.apple.com/documentation/swiftui/window

Will give it a try after fixing this issue.

**Comment by kailuo** [comment]
Fixed in https://github.com/Planetable/Planet/tree/bugfixes-window-group

Xcode 14.1 is required for new window api, now planet main app window is based on this new api, working perfectly on macOS 13, including issue 99, all resolved.

For on macOS 12, there's one issue left: https://github.com/Planetable/Planet/issues/99

**Comment by kailuo** [comment]
Added pr https://github.com/Planetable/Planet/pull/102
