### ISSUE TITLE
Use IPNS if domain name is not specified

### ISSUE THREAD

**Issue by dingwen07** [Planetable/Planet#101]
Currently, if user left blank the domain name:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/29778171/199372083-054ab875-80e3-4f5e-abee-c1182773cfa5.png">

The `<link>` items in XML file for RSS have empty domain name:

<img width="181" alt="image" src="https://user-images.githubusercontent.com/29778171/199371540-1752056b-848e-4d0c-859f-2093807fa82f.png">

Expected behavior:

Use user-specified public IPFS gateway like `cloudflare-ipfs.com` with IPNS of that Plane, if domain name is not given.

**Comment by livid** [comment]
Extra sanitization added for domain:

https://github.com/Planetable/Planet/commit/7f772a164c187242b3b2c232629165799744d2ab
