### ISSUE TITLE
how to save for new article

### ISSUE THREAD

**Issue by georgeliuyu** [Planetable/Planet#14]
![image](https://user-images.githubusercontent.com/16983441/172316055-fb5d7599-cbc8-455b-a268-60902fc75914.png)

**Comment by huabin** [comment]
You need to enter a title.

---
Bin Hua

**Comment by livid** [comment]
Please click Title and write a title.

We know this design is not good, will change it later.

**Comment by georgeliuyu** [comment]
ok,thks

**Comment by georgeliuyu** [comment]
I like your ideas, especially the follow

**Comment by georgeliuyu** [comment]
Is it normal for others to fail to follow planets posted via vpn?

**Comment by livid** [comment]
All communications between users are P2P traffic.

You probably need to try some optimization methods for IPFS:

https://docs.ipfs.io/how-to/nat-configuration/

**Comment by georgeliuyu** [comment]
Or provide a pin server that supports token payment, such as crust, that allows users to optimize

**Comment by livid** [comment]
Yes, we have a plan to create a simple Pin server so that others can run it to speed things up.

**Comment by livid** [comment]
The latest Writer in 0.8-dev

<img width="752" alt="Screen Shot 2022-07-25 at 2 01 29 AM" src="https://user-images.githubusercontent.com/11427/180739605-eec2a453-96c9-4c48-a4d8-c25681a7172a.png">
