### ISSUE TITLE
A crash in Ink 0.5.1

### ISSUE THREAD

**Issue by livid** [Planetable/Planet#15]
<img width="1424" alt="Screen Shot 2022-06-05 at 2 49 37 AM" src="https://user-images.githubusercontent.com/11427/172524522-9e06e80c-57ae-49d9-9fa7-937a02e6700c.png">

**Comment by stdc105** [comment]
This seemed to be a problem with more than one trailing newlines after markdown modifier.

**Comment by livid** [comment]
Related Fix 1:

564d794
