### ISSUE TITLE
ipfs 疯狂的收发包

### ISSUE THREAD

**Issue by ryan961** [Planetable/Planet#237]
上班挂着 planet + v2ex，收到了 it 的网络警告，看了下网络， ipfs 已经接收、发送了二三十G流量，关了重启后，重新 follow 了 https://www.v2ex.com/read.xml 才几分钟又立马飙到了 五六十 M 流量.......
![image](https://github.com/Planetable/Planet/assets/32825698/a5186916-3906-49a0-957d-d49afcd12935)
![img_v2_a598c5ec-c7b6-4fe7-862e-d97485f83bdg](https://github.com/Planetable/Planet/assets/32825698/c5bec4f9-f80a-42f5-883f-af9a8050d8a5)

**Comment by ryan961** [comment]
Version 0.13.2 (1191)

**Comment by livid** [comment]
@ryan961 

这个情况是正常的，因为 Planet 里内置了 IPFS，IPFS 所使用的 DHT 通讯确实会产生很多这样的 P2P 流量。

当产生的网络交互越多时，用 Planet 发布和订阅的 P2P 新内容也就可以越快被发现，这从内容发现的角度来说，其实是好事情。

但是如果你希望控制这块流量，可以试着修改 Planet 内置的 IPFS 的配置文件，位置在：

```
~/Library/Containers/xyz.planetable.Planet/Data/Library/Application Support/ipfs/config
```

这个配置文件的解释文档：

https://github.com/ipfs/kubo/blob/master/docs/config.md
