### ISSUE TITLE
Publishing latency

### ISSUE THREAD

**Issue by Swader** [Planetable/Planet#262]
Added Filebase but the "pinning status" bar keeps "loading". I am unable to affect it, and no errors are thrown when I say publish or build.

I tried to manually pin the JSON and images to web3.storage as well (pinnable did not work for me), but no effect - it seems like the latency is hitting the publishing process pretty hard, or the pinning is failing.

<img width="551" alt="image" src="https://github.com/Planetable/Planet/assets/1430603/dd655e76-59a7-4c8f-904a-a89db8678a30">

Would it be possible to enable some kind of dev mode so I can check what's happening with the pinning process behind the scenes?

Edit for clarification: this is not a .limo issue, it persists even if I try to "open using public gateway"

**Comment by livid** [comment]
Hi @Swader,

Thanks for the feedback. We'll add a log file on disk to show all the API request/response details. I'll let you know when this is done and released in our Insider Builds.

### Filebase Support

It was free to use when we first added the integration for Filebase API in September 2022. Later in 2022, Filebase changed terms to require a [paid plan](https://filebase.com/pricing/) (starting at $20/mo) to use their API. This is the Filebase error message I got from the debugging log. I haven't paid for my API.

<img width="586" alt="Screenshot 2023-08-21 at 11 20 39 AM" src="https://github.com/Planetable/Planet/assets/11427/9b7bedd7-9762-4427-9ff4-7b2ad5a5a41b">

### Pinnable

[Pinnable](https://pinnable.xyz) is a new pinning API we've introduced. It's specifically designed for websites running on ENS and IPNS.

First, you need to add your .eth domain to the Pinnable website. After that, copy and paste the API URL into the app. Once you've done this, the app will call this API every time you publish or rebuild.

The service and integration have just released their first version, and we'll continue to improve them.

<img width="1096" alt="Screenshot 2023-08-21 at 11 32 24 AM" src="https://github.com/Planetable/Planet/assets/11427/2f16b688-b221-4c8a-91d3-2be0c5d85db7">

**Comment by Swader** [comment]
I tried using Pinnable, and even got 0.3 eth of dwb, but the app never recognized them (I never got them in the wallet actually). Then I thought I am supposed to "redeem" but that turned out to just give me back 0.21 eth and burn all 300 tokens (which it appears I had after all?). So I could not get Pinnable to allow me to add my site. I do have a paid account on Fileverse and used that API, and in fact the first pin worked (see bruno.eth.limo) but the updated one did not, and this update has been pending now for a while. So thank you, debug logs will be appreciated to get to the bottom of it!

**Comment by Swader** [comment]
I was wrong, I had a free account on Filebase. Now that I put in a paid one, it started queueing up the pins, will see in the morning if all will be well but seems to be progressing!

**Comment by livid** [comment]
Thank you for the details.

When you first signed into planetable.xyz, it initiated a background task to check your DWB balance. If the RPC node hasn't received the block containing your transaction yet, then Pinnable might not display your DWB balance. I believe we should include additional guidance in the Pinnable UI to address this potential latency between the JB transaction and the RPC node.

Regarding the 0.09E difference, I'm curious as well. Though the project has set a 100% redemption rate, it seems like it should return more. The discrepancy is puzzling. I've inquired about it in the Juicebox discord and am currently awaiting their response.

**Comment by livid** [comment]
I got the response about how Juicebox's redemption works.

<img width="695" alt="Screenshot 2023-08-21 at 2 31 55 PM" src="https://github.com/Planetable/Planet/assets/11427/284918fc-8f8e-472b-8ca8-65d5620e4fb2">

**Comment by Swader** [comment]
That is fine, but what was more concerning is that even after 30 or so minutes my dwb did not show up in the UI, and so I was confused and blocked from using pinnable.

The Fileverse integration now says pinning (after I left it on queued overnight) but it still has not updated - my content is still out of date.

I will re-buy some dwb now to test things out with pinnable again, this latency is really quite a blocker right now.

**Comment by livid** [comment]
I'm sorry for all this! I checked with the Juicebox team and confirmed two things:

1. A recent change in Juicebox UI removed the option to claim ERC-20 tokens. These ERC-20 tokens are now internal tokens that need a claim process to become ERC-20.
2. The failed transaction to migrate legacy tokens on the UI is a bug they're aware of.

All those communications are in the Planet channel on the JB server:

https://discord.gg/juicebox

We have deployed [a fix for the process to check the DWB balance](https://github.com/PinnableXYZ/Pinnable/pull/9). You should be able to see your DWB balance on the Pinnable website.

I sent a hello on Telegram :)

**Comment by filipviz** [comment]
@Swader sorry for the issues – they should be resolved now.

- Juicebox doesn't mint legacy tokens. This is a frontend bug which should be resolved soon.
- By default, Juicebox tokens are stored as a mapping on the `JBTokenStore` contract. This allows for pretty significant gas savings over ERC-20s, and still allows for redemptions, transfers, and so on. Users can choose to claim those tokens as ERC-20s if they would like to.

You can check a user's total balance across the ERC-20 and the mapping using `JBTokenStore.balanceOf(...)`. I've switched Pinnable's backend over to this function in [this PR](https://github.com/PinnableXYZ/Pinnable/pull/9).

**Comment by Swader** [comment]
Thank you, plugged in Pinnable key into Planet now!
