### ISSUE TITLE
Garbage collection should be enabled by default

### ISSUE THREAD

**Issue by rex4539** [Planetable/Planet#390]
I notice that the repo size keeps growing. This means that garbage collection is not enabled by default.

Please enable it by default using the following command `ipfs daemon --enable-gc`.

**Comment by livid** [comment]
After adding `--enable-gc`, we observed a new issue:

IPFS kubo process no longer quits when the main Planet app quits.

It would leave zombie processes like these:

<img width="1090" alt="Screenshot 2024-12-18 at 4 51 11 PM" src="https://github.com/user-attachments/assets/2b2eee29-d8c8-488b-90fe-3dc121903ff3" />

So, we reverted the change in start parameters and added a new button for manually running garbage collection.

<img width="293" alt="Screenshot 2024-12-18 at 4 35 24 PM" src="https://github.com/user-attachments/assets/efff0337-7802-427a-a201-a7a04dbf7fc6" />

<img width="324" alt="Screenshot 2024-12-18 at 4 34 58 PM" src="https://github.com/user-attachments/assets/525200bf-2079-4ef5-a2bd-bb264a98ff55" />

It will use a local notification to let the user know GC has been performed.

<img width="376" alt="Screenshot 2024-12-18 at 4 34 49 PM" src="https://github.com/user-attachments/assets/ded117c2-422d-42c7-9759-deb85cce3569" />
