### ISSUE TITLE
Article web view is not handling download

### ISSUE THREAD

**Issue by livid** [Planetable/Planet#4]
A few methods are currently missing in our delegate implementation.

https://stackoverflow.com/questions/59083340/how-to-download-files-in-wkwebview

**Comment by livid** [comment]
@kailuo is currently working on WKDownloadDelegate for article web view.

**Comment by livid** [comment]
@kailuo is currently working on WKDownloadDelegate for article web view.

**Comment by kailuo** [comment]
Implemented and improved in:
- https://github.com/Planetable/Planet/pull/40
- https://github.com/Planetable/Planet/pull/47
- https://github.com/Planetable/Planet/pull/74
