### ISSUE TITLE
Internal Links betweens Posts

### ISSUE THREAD

**Issue by livid** [Planetable/Planet#65]
If the navigation destination is a valid UUID, set it to `PlanetStore.shared.selectedArticle`.

**Comment by livid** [comment]
Implemented the first fix:

If the last part of the URL is a UUID that exists in the current selectedArticleList, then it can be set as the current selectedArticle.

**Comment by kailuo** [comment]
[Technote -> How internal links works](https://raw.githubusercontent.com/Planetable/Planet/main/Technotes/PlanetInternalLinks.md)

**Comment by kailuo** [comment]
> Technote -> How internal links works

This was fixed and updated as described in the note.
