### ISSUE TITLE
Move articles between My Planets

### ISSUE THREAD

**Issue by livid** [Planetable/Planet#86]
One use case:

I can designate a Planet for all my Drafts and drop the completed article to another Planet for publishing.

**Comment by kailuo** [comment]
👌

**Comment by livid** [comment]
Test plan:

- [ ] Move an article with pictures
- [ ] Move an article without pictures
- [ ] Move an article with audio
- [ ] Move an article with video
- [ ] Move from/to Following Planet is not supported

**Comment by kailuo** [comment]
Started a new branch: https://github.com/Planetable/Planet/tree/move-article-command

**Comment by kailuo** [comment]
🚀 Implemented and tested, ready to be merged in pr: https://github.com/Planetable/Planet/pull/103

**Comment by kailuo** [comment]
> Test plan:
> 
> * [ *]  Move an article with pictures
> * [ *]  Move an article without pictures
> * [ *]  Move an article with audio
> * [ *]  Move an article with video
> * [ ]  Move from/to Following Planet is not supported
