### ISSUE TITLE
The application is not responding.....

### ISSUE THREAD

**Issue by ryan961** [Planetable/Planet#90]
reboot and reinstall didn't help

![image](https://user-images.githubusercontent.com/32825698/196330878-35ee0060-7c70-45f3-ba50-8672513497d1.png)

![image](https://user-images.githubusercontent.com/32825698/196330824-eed1bb10-bec6-453b-96c7-08730c3e8ba0.png)

**Comment by livid** [comment]
It seems something stuck during IPFS starting up. It should be related to network settings.

**Comment by ryan961** [comment]
I haven't made any changes to my network settings recently, it seems to go wrong after the updated version.

**Comment by livid** [comment]
Can you please try this Insider Build to see if it helps?

https://github.com/Planetable/Planet/releases/tag/insider-20221019-1
